import { useState } from "react";
import DashboardLayout from "../components/DashboardLayout";
import API from "../services/api";
import {
  UploadCloud,
  FileSpreadsheet,
  CheckCircle,
  AlertCircle,
  Loader2,
  Download,
} from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable"; // <--- FIX 1: Import as a variable

const FileTax = () => {
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleFileChange = (e) => {
    setFile(e.target.files[0]);
    setError("");
    setResult(null);
  };

  const handleUpload = async () => {
    if (!file) {
      setError("Please select a file first.");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);

    setLoading(true);
    try {
      // Send to backend
      const res = await API.post("/tax/analyze", formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      setResult(res.data);
    } catch (err) {
      setError("Failed to analyze file. Ensure it is a valid Excel file.");
    } finally {
      setLoading(false);
    }
  };

  // --- PDF GENERATION FUNCTION ---
  const generatePDF = () => {
    const doc = new jsPDF();

    // 1. Header
    doc.setFillColor(22, 163, 74); // Green color
    doc.rect(0, 0, 210, 20, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text("HelaTax - Tax Return Summary", 14, 13);

    // 2. User Info & Date
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 14, 30);
    doc.text(`Source File: ${result.fileName}`, 14, 36);

    // 3. The Table (FIX 2: Use the imported function)
    autoTable(doc, {
      startY: 45,
      head: [["Description", "Value (KES)"]],
      body: [
        ["Total Gross Income", result.totalIncome.toLocaleString()],
        ["Turnover Tax Rate", "1.5%"],
        ["Turnover Tax Payable", result.breakdown.turnoverTax.toLocaleString()],
        ["Net Income", result.breakdown.netIncome.toLocaleString()],
      ],
      theme: "grid",
      headStyles: { fillColor: [22, 163, 74] },
    });

    // 4. Footer / Disclaimer
    // (FIX 3: Access finalY from the 'lastAutoTable' property on doc)
    const finalY = doc.lastAutoTable.finalY + 10;

    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text(
      "Disclaimer: This document is an estimate generated by HelaTax AI. Please verify with KRA iTax.",
      14,
      finalY
    );

    // 5. Save
    doc.save("HelaTax_Return_Summary.pdf");
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto">
        <h2 className="text-2xl font-bold text-slate-900 mb-6">File Returns</h2>

        {/* 1. UPLOAD SECTION */}
        <div className="bg-white p-8 rounded-3xl border border-slate-100 shadow-sm text-center">
          <div className="w-16 h-16 bg-green-50 text-green-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <UploadCloud size={32} />
          </div>
          <h3 className="text-lg font-bold text-slate-800 mb-2">
            Upload your P9 or Income Sheet
          </h3>
          <p className="text-slate-500 mb-6">
            Supports .xlsx or .csv files. Ensure you have an "Amount" column.
          </p>

          <input
            type="file"
            accept=".xlsx, .xls, .csv"
            onChange={handleFileChange}
            className="hidden"
            id="fileInput"
          />

          <label
            htmlFor="fileInput"
            className="cursor-pointer inline-flex items-center gap-2 px-6 py-3 bg-slate-100 text-slate-700 font-bold rounded-xl hover:bg-slate-200 transition"
          >
            {file ? file.name : "Choose File"}
          </label>

          <div className="mt-6">
            <button
              onClick={handleUpload}
              disabled={!file || loading}
              className="px-8 py-3 bg-green-600 text-white font-bold rounded-xl hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed transition shadow-lg shadow-green-200"
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <Loader2 className="animate-spin" /> Analyzing...
                </span>
              ) : (
                "Analyze & Calculate Tax"
              )}
            </button>
          </div>

          {error && (
            <div className="mt-4 text-red-500 flex items-center justify-center gap-2 font-medium">
              <AlertCircle size={16} /> {error}
            </div>
          )}
        </div>

        {/* 2. RESULTS SECTION */}
        {result && (
          <div className="mt-8 animate-fade-in-up">
            {/* Header with Download Button */}
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                <CheckCircle className="text-green-500" /> Analysis Complete
              </h3>
              <button
                onClick={generatePDF}
                className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white text-sm font-bold rounded-lg hover:bg-slate-800 transition shadow-md"
              >
                <Download size={16} /> Download PDF
              </button>
            </div>

            <div className="grid md:grid-cols-3 gap-6">
              {/* Total Income Card */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                <p className="text-slate-500 text-sm font-medium mb-1">
                  Total Gross Income
                </p>
                <p className="text-2xl font-bold text-slate-900">
                  KES {result.totalIncome.toLocaleString()}
                </p>
              </div>

              {/* Turnover Tax Card */}
              <div className="bg-white p-6 rounded-2xl border border-green-200 bg-green-50/50 shadow-sm">
                <p className="text-green-700 text-sm font-medium mb-1">
                  Turnover Tax (1.5%)
                </p>
                <p className="text-2xl font-bold text-green-700">
                  KES {result.breakdown.turnoverTax.toLocaleString()}
                </p>
              </div>

              {/* Net Income Card */}
              <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                <p className="text-slate-500 text-sm font-medium mb-1">
                  Net Income
                </p>
                <p className="text-2xl font-bold text-slate-900">
                  KES {result.breakdown.netIncome.toLocaleString()}
                </p>
              </div>
            </div>

            <div className="mt-6 p-4 bg-blue-50 border border-blue-100 rounded-xl text-blue-700 text-sm flex items-center gap-3">
              <AlertCircle size={20} />
              Based on <strong>{result.totalRows} rows</strong> of data found in{" "}
              <em>{result.fileName}</em>.
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
};

export default FileTax;
